"""Evidence Vault: structured legal / ecological metadata for archived spills + reconstructed day-by-day footprint frames."""
import math
from datetime import timedelta
from typing import List

# name → legal & ecological evidence (public sources)
VAULT = {
    "Deepwater Horizon (Macondo)": {"duration_days": 87, "max_area_km2": 149000, "ruling": "US District Court (E.D. La.) 2014 found BP grossly negligent under the Clean Water Act; 2016 consent decree.", "penalties": "US$20.8 bn settlement (largest environmental settlement in US history) + US$4 bn criminal plea (2012).", "cleanup_cost": "≈ US$14 bn response cost; total BP liabilities > US$65 bn.", "compensation": "US$5.5 bn CWA penalty, US$8.8 bn natural-resource damages, US$5.9 bn to states/localities.", "ecological": "Deepwater coral mortality, dolphin & sea-turtle die-offs, ~1,100 km oiled shoreline; multi-decade NRDA monitoring.", "sources": [{"t": "US DOJ consent decree", "u": "https://www.justice.gov/enrd/deepwater-horizon"}, {"t": "NOAA DWH NRDA", "u": "https://www.gulfspillrestoration.noaa.gov/"}]},
    "Exxon Valdez": {"duration_days": 60, "max_area_km2": 28000, "ruling": "Exxon Shipping Co. v. Baker (US Supreme Court, 2008) capped punitive damages at 1:1 to compensatory.", "penalties": "US$125 m criminal (1991 plea), US$900 m civil settlement.", "cleanup_cost": "≈ US$2.1 bn.", "compensation": "US$507.5 m punitive to ~32,000 plaintiffs after Supreme Court reduction.", "ecological": "≈250,000 seabirds, 2,800 sea otters, 300 harbour seals; herring collapse 1993; lingering subsurface oil decades later.", "sources": [{"t": "EVOS Trustee Council", "u": "https://evostc.state.ak.us/"}, {"t": "Exxon v. Baker", "u": "https://supreme.justia.com/cases/federal/us/554/471/"}]},
    "Prestige": {"duration_days": 45, "max_area_km2": 10000, "ruling": "Spanish Supreme Court 2016 convicted the master of reckless environmental crime and held the owner/insurer (London P&I) liable up to US$1 bn.", "penalties": "Master 2-year sentence; civil liability ~€1.5 bn assessed.", "cleanup_cost": "≈ €2.5 bn including fisheries losses.", "compensation": "IOPC Fund paid up to the €171.5 m CLC/Fund limit; Spain sued the classification society (ABS) in the US unsuccessfully.", "ecological": ">2,000 km of coast oiled; 115,000–230,000 seabirds estimated killed; shellfish grounds closed 6 months.", "sources": [{"t": "IOPC Funds incident page", "u": "https://iopcfunds.org/incidents/incident-map/#100-2002-190-November"}, {"t": "CEDRE Prestige", "u": "https://wwz.cedre.fr/en/Resources/Spills/Spills/Prestige"}]},
    "Erika": {"duration_days": 30, "max_area_km2": 4000, "ruling": "Cour de cassation (2012) upheld Total SA's criminal conviction and recognised 'préjudice écologique' (pure ecological damage) as compensable.", "penalties": "€375,000 fine (Total) + damages ~€200 m.", "cleanup_cost": "≈ €200 m response; economic losses ~€1 bn.", "compensation": "IOPC Fund + Total voluntary payments ≈ €200 m; landmark ecological-damage award.", "ecological": ">60,000 seabirds oiled (largest European bird kill); 400 km coast; oyster farms closed.", "sources": [{"t": "Cour de cassation 25 Sept 2012", "u": "https://www.courdecassation.fr/"}, {"t": "IOPC Funds Erika", "u": "https://iopcfunds.org/incidents/"}]},
    "Sanchi": {"duration_days": 14, "max_area_km2": 300, "ruling": "Investigation by Iran/China/Panama; no criminal ruling; flag-state MSA reports on collision liability.", "penalties": "Liability apportioned between CF Crystal and Sanchi owners (collision).", "cleanup_cost": "Limited — condensate evaporated/burned; monitoring costs.", "compensation": "Claims via Panama-flag insurers; 32 crew lost (no survivors).", "ecological": "Condensate toxicity to plankton/fish larvae; Japan Ryukyu beaches received clumps; fisheries advisories East China Sea.", "sources": [{"t": "ITOPF Sanchi", "u": "https://www.itopf.org/in-action/case-studies/sanchi-east-china-sea-2018/"}]},
    "MV Wakashio": {"duration_days": 25, "max_area_km2": 30, "ruling": "Mauritius court 2021 convicted captain & first officer (20 months) for endangering safe navigation.", "penalties": "Owner Nagashiki Shipping capped liability under LLMC; Mauritius sought ~US$34 m.", "cleanup_cost": "≈ US$34 m claimed for cleanup and rehabilitation.", "compensation": "Owner/insurer (Japan P&I) paid fishermen & tourism compensation; Japan JICA reef restoration aid.", "ecological": "Blue Bay Marine Park and Île aux Aigrettes mangroves oiled; 39 dolphins/whales stranded; VLSFO persistence in mangroves.", "sources": [{"t": "ITOPF Wakashio", "u": "https://www.itopf.org/in-action/case-studies/wakashio-mauritius-2020/"}]},
    "MT Dawn Kanchipuram – Chennai (Ennore) collision": {"duration_days": 20, "max_area_km2": 40, "ruling": "DG Shipping inquiry; Madras High Court PIL (2017) on response failures; NGT directed compensation assessment.", "penalties": "Ship-owners' P&I clubs funded cleanup; no criminal conviction reported.", "cleanup_cost": "≈ ₹ 4–5 crore reported cleanup; volunteer-driven manual removal of ~250 t sludge.", "compensation": "Fisher compensation ordered by TN government (₹ 1,000/day interim); NGT monitoring.", "ecological": "34 km Ennore–Marina coastline oiled; olive ridley nesting season impacted; fisheries losses for ~3 weeks.", "sources": [{"t": "ICG press release 2017", "u": "https://indiancoastguard.gov.in/"}, {"t": "NGT Southern Zone orders", "u": "https://www.greentribunal.gov.in/"}]},
    "Ennore / Kamarajar Port spill (Cyclone Michaung)": {"duration_days": 25, "max_area_km2": 20, "ruling": "NGT (Southern Zone) 2024 imposed interim environmental compensation on CPCL; TNPCB directions.", "penalties": "₹ 5 crore interim environmental compensation (NGT, 2024) on CPCL.", "cleanup_cost": "CPCL-funded creek cleanup with contractors; Coast Guard booms.", "compensation": "TN government relief to ~6,000 affected fisher families.", "ecological": "Ennore creek & Kosasthalaiyar mangroves, Buckingham Canal oiled; fish/crab mortality.", "sources": [{"t": "NGT SZ order (Ennore oil spill)", "u": "https://www.greentribunal.gov.in/"}]},
    "Hebei Spirit": {"duration_days": 45, "max_area_km2": 15000, "ruling": "Korean Supreme Court 2009 held Samsung Heavy Industries' tug negligent; tanker master acquitted on appeal.", "penalties": "Samsung: KRW 30 m fine; liability capped at KRW 5.6 bn under LLMC (controversial).", "cleanup_cost": "≈ US$300 m+.", "compensation": "IOPC 1992 Fund ~US$200 m + Korean special act; ~128,000 claims.", "ecological": "375 km Taean coast; aquaculture & tidal flats damaged; 1.2 M volunteers mobilised.", "sources": [{"t": "IOPC Funds Hebei Spirit", "u": "https://iopcfunds.org/incidents/"}]},
    "Amoco Cadiz": {"duration_days": 60, "max_area_km2": 5000, "ruling": "US District Court (N.D. Ill.) 1984–1992 found Amoco liable (defective steering gear, inadequate maintenance).", "penalties": "US$204 m damages (1992) to France and Brittany communes.", "cleanup_cost": "≈ FRF 500 m; largest cleanup of its era.", "compensation": "US$204 m awarded after 14 years of litigation.", "ecological": "360 km coast; 20,000 birds; oyster beds destroyed; marshes took 7+ years to recover.", "sources": [{"t": "CEDRE Amoco Cadiz", "u": "https://wwz.cedre.fr/en/Resources/Spills/Spills/Amoco-Cadiz"}]},
    "Torrey Canyon": {"duration_days": 30, "max_area_km2": 700, "ruling": "Settled 1969 (UK/France vs Barracuda Tanker Corp) after arrest of sister ship; led to CLC 1969 & Intervention Convention.", "penalties": "£3 m settlement shared UK/France.", "cleanup_cost": "≈ £2 m UK; detergents and RAF bombing.", "compensation": "£3 m settlement.", "ecological": "~15,000 seabirds; toxic detergents devastated intertidal life (recovery 10–15 years).", "sources": [{"t": "ITOPF Torrey Canyon", "u": "https://www.itopf.org/in-action/case-studies/torrey-canyon-united-kingdom-1967/"}]},
    "X-Press Pearl": {"duration_days": 40, "max_area_km2": 200, "ruling": "Sri Lanka Supreme Court 2025 ordered owner to pay US$1 bn initial compensation (fundamental-rights petitions); UK admiralty limitation proceedings ongoing.", "penalties": "US$1 bn SC order; interim US$7.85 m paid by owner (2021–22).", "cleanup_cost": "Nurdle cleanup ongoing; UNEP estimated damages US$6.4 bn.", "compensation": "Fisher relief ~LKR 1.2 bn interim; UNEP/Sri Lanka claims process.", "ecological": "1,680 t plastic nurdles (worst maritime plastic spill), 400+ turtles and 50 dolphins dead; Negombo lagoon fisheries closed.", "sources": [{"t": "UNEP X-Press Pearl report", "u": "https://www.unep.org/resources/report/x-press-pearl-maritime-disaster-sri-lanka"}, {"t": "Sri Lanka Supreme Court judgment 2025", "u": "https://www.supremecourt.lk/"}]},
    "MSC ELSA 3 — Kochi oil slick": {"duration_days": 20, "max_area_km2": 50, "ruling": "Kerala govt filed an admiralty suit in the Kerala High Court under the Admiralty (Jurisdiction and Settlement of Maritime Claims) Act, 2017; HC ordered conditional arrest of sister vessel MSC Akiteta-2 at Vizhinjam (7 Jul 2025), modified 25 Sep 2025 to reduce interim security to ₹1,227.62 crore (litigation ongoing).", "penalties": "Interim security of ₹1,227.62 crore ordered for release of the arrested sister ship (not final compensation); ₹500 cr for oil-pollution damage within that figure.", "cleanup_cost": "Indian Coast Guard aerial mapping + offshore dispersant response; wreck bunker-oil removed by hot-tapping (completed Oct 2025).", "compensation": "Kerala's admiralty claim sought ₹9,531.11 crore total (₹8,626.12 cr environmental/coastal, ₹378.48 cr remediation/prevention, ₹526.51 cr economic loss to fishers); interim fisher-loss security ~₹349 cr market impact + ₹71 cr for the 6-month fishing ban within 20 nm.", "ecological": "Bunker fuel (367.1 t furnace oil + 84.44 t diesel) plus hazardous containers (12 calcium carbide + 1 organic chemical); 6-month fishing ban within 20 nm of the wreck; container debris on Alappuzha/Kollam/Thiruvananthapuram beaches; all 24 crew rescued.", "sources": [{"t": "Kerala SDMA — Ship wreck MSC ELSA 3", "u": "https://sdma.kerala.gov.in/ship-wreck-msc-elsa-3/"}, {"t": "The Hindu — HC reduces security to ₹1,227.62 cr", "u": "https://www.thehindu.com/news/national/kerala/compensation-for-sinking-of-msc-elsa-3-hc-reduces-security-amount-to-122762-cr/article70093743.ece"}, {"t": "LiveLaw — Kerala HC admiralty suit", "u": "https://www.livelaw.in/high-court/kerala-high-court/kerala-high-court-state-admiralty-suit-msc-elsa-compensation-305173"}]},
    "MV Wan Hai 503 fire off Kerala (Beypore)": {"duration_days": 15, "max_area_km2": 60, "ruling": "Kerala SDMA-coordinated response with DG Shipping / salvage oversight; liability and compensation assessment ongoing (as in the MSC ELSA 3 case).", "penalties": "Owner/salvor liability under assessment; proceedings ongoing.", "cleanup_cost": "ICG intensive firefighting & boundary cooling + IAF MI-17 dry-chemical drops; offshore salvage tow to move the burning vessel further out and reduce coastal risk.", "compensation": "Fisher and coastal-impact assessment along Kozhikode–Kochi ongoing.", "ecological": "~2,128 t bunker fuel (HFO + diesel) and 143–157 hazardous containers at risk; ~50 containers overboard; hydrocarbon release detected near fuel tanks; INCOIS forecast 70–80% S-SE drift toward Kozhikode–Kochi; of 22 crew 18 rescued, 4 missing.", "sources": [{"t": "Kerala SDMA — Ship wreck Wan Hai 503", "u": "https://sdma.kerala.gov.in/ship-wreck-wanhai-503/"}, {"t": "The Hindu — hydrocarbon release detected", "u": "https://www.thehindu.com/news/cities/Thiruvananthapuram/ship-on-fire-hydrocarbon-release-detected-near-fuel-tank-of-burning-ship/article69685454.ece"}, {"t": "AP News — Wan Hai ship fire off Kerala", "u": "https://apnews.com/article/singapore-wan-hai-ship-fire-coast-kerala-9b7f9b461d93c7ed427a715b32a74ec8"}]},
    "2010 Mumbai oil spill (MSC Chitra – MV Khalijia III collision)": {"duration_days": 30, "max_area_km2": 300, "ruling": "DG Shipping inquiry + Bombay HC proceedings; MPCB with NEERI/NIO/TERI ran the impact assessment; owners' P&I funded the response. No major criminal conviction reported.", "penalties": "Response and damage costs borne by the owners/insurers; MPCB pursued remediation compliance.", "cleanup_cost": "Multi-agency ICG + state cleanup over a ~110 km shoreline with months of monitoring.", "compensation": "Fisher losses during the Mumbai-harbour traffic suspension; claims pursued via owners' insurers.", "ecological": "~400–879 t oil across Mumbai/Thane/Raigad; mangroves and Juhu/Uran beaches oiled; ~400 containers (31 hazardous, incl. organophosphate pesticides) lost at sea.", "sources": [{"t": "MPCB oil-spill report (Arabian Sea)", "u": "https://www.mpcb.gov.in/sites/default/files/oil-spill/Report_Oil%20Spill_%20Arbian%20Sea.pdf"}, {"t": "Wikipedia — 2010 Mumbai oil spill", "u": "https://en.wikipedia.org/wiki/2010_Mumbai_oil_spill"}, {"t": "ITOPF Interspill 2012 paper", "u": "https://www.itopf.org/fileadmin/uploads/itopf/data/Documents/Papers/interspill12_ohagan_000.pdf"}]},
    "MV Rak Carrier sinking off Mumbai": {"duration_days": 20, "max_area_km2": 100, "ruling": "DG Shipping inquiry found poor maintenance and ineffective owner monitoring as the cause; the captain and chief engineer were arrested (2011).", "penalties": "Criminal proceedings against the master/chief engineer; owner liability for the cleanup.", "cleanup_cost": "ICG 'Operation Paryavaran Suraksha 02/2011' dispersant operation + state shoreline cleanup.", "compensation": "Claims pursued via the owners; coastal fisher impact along the Mumbai–Raigad coast.", "ecological": "~290 t fuel oil leaked from the wreck (~1.5–2 t/hr initially, of ~340 t onboard); oil patches at Juhu, Bandra, Gorai and Alibaug; mangroves affected.", "sources": [{"t": "MPCB MV Rak final report (2013)", "u": "https://mpcb.ecmpcb.in/hazardous/pdf/OILSPILL_MVRAK_finalReportApril-2013.pdf"}, {"t": "CEDRE — Rak Carrier", "u": "https://wwz.cedre.fr/en/Resources/Spills/Spills/Rak-Carrier"}, {"t": "PIB — inquiry release", "u": "https://www.pib.gov.in/newsite/PrintRelease.aspx?relid=77666"}]},
    "Bombay High North platform fire (ONGC)": {"duration_days": 5, "max_area_km2": 30, "ruling": "ONGC/DG Shipping inquiry + ICheME/OISD incident analyses; led to strengthened OISD offshore-safety regulatory powers. No public criminal conviction reported.", "penalties": "Regulatory reforms rather than fines; insurers covered the platform (US$195 m) and the MSV (US$60 m).", "cleanup_cost": "~US$370 m total loss; MSV Samudra Suraksha caught fire and sank under tow (1 Aug 2005).", "compensation": "Insurance settlements; ex-gratia to the families of the 22 deceased.", "ecological": "Jet fire destroyed a four-platform crude/gas complex ~100 km off Mumbai with hydrocarbon release; 22 fatalities, 362 of 384 rescued.", "sources": [{"t": "Wikipedia — 2005 Mumbai High fire", "u": "https://en.wikipedia.org/wiki/2005_Mumbai_High_fire"}, {"t": "ICheME — MHN incident summary (27 Jul 2005)", "u": "https://www.icheme.org/media/14085/mumbai-high-north-incident-summary-27-jul-05.pdf"}]},
    "MV River Princess grounding — Goa (Candolim)": {"duration_days": 30, "max_area_km2": 20, "ruling": "Declared a 'nuisance' (2003) and a state disaster (2009); Bombay HC (Goa bench, Mar 2025) quashed the state's ₹166.4 cr recovery bill against charterer Salgaocar and ordered fresh determination of removal costs.", "penalties": "State sought ₹166.4 cr removal-cost recovery from the charterer (under fresh HC-ordered determination as of 2025).", "cleanup_cost": "₹99 cr in-situ dismantling contract (Arihant, 2011); NIO/GSL seabed debris removal to 2014.", "compensation": "Cost-recovery litigation with the charterer ongoing.", "ecological": "~0.13 km² of Candolim beach lost to wreck-induced erosion over 12+ years; localized residual-oil leaks; the remains now form a small artificial reef.", "sources": [{"t": "The Hindu — the saga of MV River Princess", "u": "https://www.thehindu.com/news/cities/Mangalore/the-saga-of-mv-river-princess/article29838357.ece"}, {"t": "TOI — HC quashes ₹166 cr salvage bill", "u": "https://timesofindia.indiatimes.com/city/goa/hc-quashes-states-rs-166cr-bill-levied-to-salvage-salgaocars-river-princess/articleshow/119314875.cms"}]},
    "Ennore ammonia subsea-pipeline leak (Coromandel International)": {"duration_days": 3, "max_area_km2": 5, "ruling": "NGT took suo-motu cognisance; TNPCB suspended plant operations pending damage repair and recertification by the TN Maritime Board and the Indian Register of Shipping.", "penalties": "Operations suspended; environmental-compliance directions by TNPCB/NGT.", "cleanup_cost": "Medical response (~60 hospitalised) + pipeline repair/recertification borne by the operator.", "compensation": "Relief to affected Ennore fisher hamlets; NGT monitoring.", "ecological": "~67.6 t ammonia in ~15 min; seawater ammonia 49 mg/L (vs 5 mg/L marine-discharge standard), ambient air 3 ppm; fish/aquatic kills near Periyakuppam/Chinnakuppam. CHEMICAL release — not oil.", "sources": [{"t": "The Hindu — 67.6 t ammonia estimate (NGT committee)", "u": "https://www.thehindu.com/news/cities/chennai/676-tonnes-of-ammonia-gas-estimated-to-have-leaked-from-fertilizer-unit-pipeline-in-ennore-committee-tells-ngt/article67818054.ece"}, {"t": "Indian Express — Ennore ammonia leak", "u": "https://indianexpress.com/article/cities/chennai/ammonia-gas-leaks-chennai-fertiliser-unit-36-under-treatment-9085505/"}]},
}


def reconstruct_frames(entry: dict) -> List[dict]:
    """Day-by-day RECONSTRUCTED footprint: area grows ∝ √t to max_area_km2 then weathers/disperses. Not a satellite record."""
    v = VAULT.get(entry["name"], {})
    days = int(v.get("duration_days") or max(3, min(60, round((entry.get("volume_tonnes") or 100) ** 0.33))))
    a_max = float(v.get("max_area_km2") or max(2.0, (entry.get("volume_tonnes") or 100) * 0.05))
    frames = []
    for d in range(1, days + 1):
        frac = math.sqrt(min(1.0, d / (days * 0.6))) * (1.0 if d <= days * 0.6 else max(0.15, 1 - (d - days * 0.6) / (days * 0.5)))
        area = a_max * frac
        r_km = math.sqrt(area / math.pi)
        frames.append({"day": d, "date": entry["date"] + timedelta(days=d - 1), "area_km2": round(area, 1), "radius_km": round(r_km, 2), "elongation": 2.0 + 0.05 * d})
    return frames
